### ISSUE TITLE
2-employee-creation-page

### ISSUE THREAD

**Issue by Cecilia-Giusti** [Cecilia-Giusti/P-14-wealth-health#2]
_As a user I want to be able to access the employee creation page_

**Design :** 

Desktop : 

![Image](https://user-images.githubusercontent.com/61047121/196938269-5b3e0413-239c-4a51-b151-43cc8b8d4337.jpg)

[Figma for tablet and smartphone views](https://www.figma.com/file/tiRFFGo00Z3reuHAv03BJI/Untitled?node-id=4%3A139)

**Tasks :** 

- [x] React initialization and librairies
- [x] Creation of the page with React and a new design
- [x] Add date plugin
- [x] Add select plugin
- [x] Add modal plugin
- [x] Add logic
